name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    name: Check Code Formatting
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Find clang-format and run check
      run: .\housekeeper.ps1 -CheckFormat
      shell: pwsh 
      
  build:
    name: Build Project
    runs-on: windows-latest
    needs: format_check # This job will only run if 'format_check' succeeds

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up MSVC environment with Vcpkg and Python
      # This action sets up MSVC, CMake, Ninja, and other necessary tools.
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64 

    - name: Install Vcpkg Dependencies
      # This step calls housekeeper script to handle vcpkg setup and dependency installation.
      run: .\housekeeper.ps1 -Deps
      shell: pwsh 

    - name: Build Project (Release)
      run: .\housekeeper.ps1 -Build -Config Release
      shell: pwsh 

    - name: Build Project (Debug)
      run: .\housekeeper.ps1 -Build -Config Debug
      shell: pwsh 