name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format_check:
    name: Check Code Formatting
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Vcpkg Setup
      id: vcpkg_setup
      uses: ./.github/actions/vcpkg-setup/
      
    - name: Find clang-format and run check
      run: |
        $env:VCPKG_ROOT = "${{ steps.vcpkg_setup.outputs.vcpkg_root }}"
        $env:CMAKE_TOOLCHAIN_FILE = "${{ steps.vcpkg_setup.outputs.cmake_toolchain_file }}"
        .\Housekeeper\housekeeper.ps1 -CheckFormat
      shell: pwsh
      
  build:
    name: Build Project
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Vcpkg Setup
      id: vcpkg_setup
      uses: ./.github/actions/vcpkg-setup/
      
    - name: Add MSBuild and Developer Command Prompt to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Vcpkg Dependencies
      run: |
        $env:VCPKG_ROOT = "${{ steps.vcpkg_setup.outputs.vcpkg_root }}"
        $env:CMAKE_TOOLCHAIN_FILE = "${{ steps.vcpkg_setup.outputs.cmake_toolchain_file }}"
        .\Housekeeper\housekeeper.ps1 -Deps
      shell: pwsh

    - name: Build Project (Debug)
      run: |
        $env:VCPKG_ROOT = "${{ steps.vcpkg_setup.outputs.vcpkg_root }}"
        $env:CMAKE_TOOLCHAIN_FILE = "${{ steps.vcpkg_setup.outputs.cmake_toolchain_file }}"
        .\Housekeeper\housekeeper.ps1 -Build -Config Debug
      shell: pwsh

    - name: Build Project (Release)
      run: |
        $env:VCPKG_ROOT = "${{ steps.vcpkg_setup.outputs.vcpkg_root }}"
        $env:CMAKE_TOOLCHAIN_FILE = "${{ steps.vcpkg_setup.outputs.cmake_toolchain_file }}"
        .\Housekeeper\housekeeper.ps1 -Build -Config Release
      shell: pwsh
